### ISSUE TITLE
[一个错误的报告，与此插件无关]当玩家传送到另一个子服时报错

### ISSUE THREAD

**Issue by lipind** [RIA-AED/TrafficTool#2]
java.lang.NullPointerException: Cannot invoke "com.velocitypowered.proxy.protocol.packet.chat.ComponentHolder.getJson()" because "holder" is null
[23:28:43 ERROR]:       at com.loohp.interactivechat.proxy.velocity.InteractiveChatVelocity$2.write(InteractiveChatVelocity.java:933)
[23:28:43 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[23:28:43 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[23:28:43 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[23:28:43 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[23:28:43 ERROR]:       at io.netty.handler.traffic.GlobalTrafficShapingHandler.submitWrite(GlobalTrafficShapingHandler.java:349)
[23:28:43 ERROR]:       at io.netty.handler.traffic.AbstractTrafficShapingHandler.write(AbstractTrafficShapingHandler.java:569)
[23:28:43 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[23:28:43 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[23:28:43 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[23:28:43 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[23:28:43 ERROR]:       at io.netty.handler.traffic.ChannelTrafficShapingHandler.submitWrite(ChannelTrafficShapingHandler.java:186)
[23:28:43 ERROR]:       at io.netty.handler.traffic.AbstractTrafficShapingHandler.write(AbstractTrafficShapingHandler.java:569)
[23:28:43 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[23:28:43 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[23:28:43 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[23:28:43 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[23:28:43 ERROR]:       at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[23:28:43 ERROR]:       at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[23:28:43 ERROR]:       at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:248)
[23:28:43 ERROR]:       at com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler.handleBackendJoinGame(ClientPlaySessionHandler.java:555)
[23:28:43 ERROR]:       at com.velocitypowered.proxy.connection.backend.TransitionSessionHandler.lambda$handle$0(TransitionSessionHandler.java:134)
[23:28:43 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
[23:28:43 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[23:28:43 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[23:28:43 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)

[23:28:43 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[23:28:43 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[23:28:43 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[23:28:43 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[23:28:43 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[23:28:43 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Ghost-chu** [comment]
关闭 TrafficTool 再次尝试，TT工具不会改写数据包，通常并非由 TrafficTool 引发

**Comment by lipind** [comment]
抱歉抱歉，我搞混了，这是要反馈给另一个插件的报错，
TrafficTool非常棒，而且测试有效：）
